---
- name: Ping
  hosts: windows
  gather_facts: no
  vars:
    #ansible_ssh_user: "wavenet"
    #ansible_ssh_pass: "Bejerman23$"
    ansible_user: "wavenet"
    #ansible_password: "Bejerman23$"
    ansible_password: "Bejerman21!"
    ansible_ssh_port: "5985"
    ansible_connection: "winrm"
    ansible_winrm_server_cert_validation: ignore

    password_length: 10


  tasks:
    - name: Ping Windows Hosts
      win_ping:
